[package]
name = "encyclopedia"
version = "0.1.0"
edition = "2021"

[dependencies]
units = { path = "../Units" }
combat = { path = "../Combat" }
graphics = { path = "../Graphics" }
items = { path = "../Items" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
